name: Build All

on: [push,pull_request]
jobs:
  build_all:
    name: "Build entire project"

    runs-on: ubuntu-latest
    container: ubuntu:22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt-get update && apt-get upgrade -y
        apt-get install clang make xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules -y
    - name: Generate Make Projects
      run: |
        ./vendor/premake/premake5 gmake2 --cc=clang

    - name: Build debug
      run: |
        make config=debug -j${nproc}
    - name: Build release
      run: |
        make config=release -j${nproc}
